const UserActionType = {
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  SIGNIN_SUCCESS: "GOOGLE_SIGNIN_SUCCESS",
  SIGNIN_ERROR: "GOOGLE_SIGNIN_ERROR",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_ERROR: "SIGN_OUT_ERROR",
  REGISTRATION_START: "REGISTRATION_START",
  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_ERROR: "REGISTRATION_ERROR",
};

export default UserActionType;
